import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        URL: "readonly",
        Blob: "readonly",
        File: "readonly",
        Audio: "readonly",
        Image: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        Uint8Array: "readonly",
        btoa: "readonly",
        atob: "readonly",
        HTMLElement: "readonly",
        NodeFilter: "readonly",
        Range: "readonly",
        DOMParser: "readonly",
        fetch: "readonly",
        Response: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        self: "readonly",
        clients: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        indexedDB: "readonly",
        AbortController: "readonly",
        URLSearchParams: "readonly",
        OfflineAudioContext: "readonly",
        getComputedStyle: "readonly",
        requestAnimationFrame: "readonly",
        crypto: "readonly",
        caches: "readonly",
        Intl: "readonly",
        location: "readonly",
        history: "readonly",
        MediaMetadata: "readonly",
        SpeechSynthesisUtterance: "readonly",
        speechSynthesis: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-console": "off",
      "prefer-const": "error",
      "no-var": "error",
      eqeqeq: ["error", "smart"],
    },
  },
  {
    files: ["scripts/**/*.js"],
    languageOptions: {
      globals: {
        require: "readonly",
        module: "readonly",
        exports: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        process: "readonly",
        Buffer: "readonly",
        crypto: "readonly",
        fetch: "readonly",
        btoa: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        console: "readonly",
      },
    },
  },
  {
    ignores: ["node_modules/", "docs/coi-serviceworker.js"],
  },
];
