/**
 * version.js — one version number, four places.
 *
 * package.json holds the source of truth: `version` (what people see) and
 * `build` (the service-worker cache generation, bumped on every release so a
 * deploy actually reaches installed PWAs). Everything else is written from it:
 *
 *   docs/js/version.js   VERSION / BUILD, imported by the app
 *   docs/sw.js           CACHE_NAME + RUNTIME_CACHE suffix
 *   docs/index.html      the Settings → Version row
 *   ios/project.yml      MARKETING_VERSION / CURRENT_PROJECT_VERSION
 *
 * Usage:
 *   node scripts/version.js              sync the targets from package.json
 *   node scripts/version.js --check      verify they agree (CI); exit 1 if not
 *   node scripts/version.js 2.1.0        set the version, bump the build, sync
 *   node scripts/version.js --bump       bump the build only, sync
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const at = (p) => root + p;
const read = (p) => readFileSync(at(p), "utf8");

// A rewrite rule: find `re` in the file, rebuild the match from the version.
const TARGETS = [
  {
    file: "docs/js/version.js",
    // generated wholesale — no regex, the whole file is ours
    render: ({ version, build }) => `/**
 * version.js — generated by \`npm run version\`. Do not edit by hand.
 * Source of truth: the "version" and "build" fields in package.json.
 */

export const VERSION = "${version}";
export const BUILD = ${build};
`,
  },
  {
    file: "docs/sw.js",
    rules: [
      { re: /(const CACHE_NAME = 'pageturner-cache-v)(\d+)(')/, val: ({ build }) => build },
      { re: /(const RUNTIME_CACHE = 'pageturner-runtime-v)(\d+)(')/, val: ({ build }) => build },
    ],
  },
  {
    file: "docs/index.html",
    rules: [
      { re: /(id="set-version">)([^<]*)(<)/, val: ({ version }) => version },
    ],
  },
  {
    // only the root package's own version — rewriting the lockfile with npm
    // can reshuffle platform fields depending on the local npm's age
    file: "package-lock.json",
    rules: [
      { re: /^(\{\s*"name": "pageturner",\s*"version": ")([^"]*)(")/, val: ({ version }) => version },
      { re: /("packages": \{\s*"": \{\s*"name": "pageturner",\s*"version": ")([^"]*)(")/, val: ({ version }) => version },
    ],
  },
  {
    file: "ios/project.yml",
    rules: [
      { re: /(MARKETING_VERSION: ")([^"]*)(")/, val: ({ version }) => version },
      { re: /(CURRENT_PROJECT_VERSION: ")([^"]*)(")/, val: ({ build }) => build },
    ],
  },
];

const pkgPath = "package.json";
const pkg = JSON.parse(read(pkgPath));

const bumpArg = process.argv.includes("--bump");
const checkArg = process.argv.includes("--check");
const setArg = process.argv.slice(2).find((a) => /^\d+\.\d+\.\d+$/.test(a));

if (checkArg && (bumpArg || setArg)) {
  console.error("--check can't be combined with a bump or a new version.");
  process.exit(2);
}

let version = pkg.version;
let build = Number(pkg.build);
if (!Number.isInteger(build) || build < 1) {
  console.error(`package.json needs an integer "build" field (found ${JSON.stringify(pkg.build)}).`);
  process.exit(2);
}
if (setArg) version = setArg;
if (setArg || bumpArg) build += 1;

const source = { version, build };

/** Apply a target's rules to its text. Returns { text, mismatches }. */
const applyRules = (file, rules, text) => {
  const mismatches = [];
  let out = text;
  for (const { re, val } of rules) {
    const m = out.match(re);
    if (!m) {
      mismatches.push({ file, want: String(val(source)), found: null });
      continue;
    }
    const want = String(val(source));
    if (m[2] !== want) mismatches.push({ file, want, found: m[2] });
    out = out.replace(re, (_, a, __, c) => a + want + c);
  }
  return { text: out, mismatches };
};

const mismatches = [];
const writes = [];
for (const target of TARGETS) {
  const current = read(target.file);
  if (target.render) {
    const next = target.render(source);
    if (next !== current) mismatches.push({ file: target.file, want: `${source.version} / ${source.build}`, found: "out of date" });
    if (next !== current) writes.push([target.file, next]);
    continue;
  }
  const { text, mismatches: ms } = applyRules(target.file, target.rules, current);
  mismatches.push(...ms);
  if (text !== current) writes.push([target.file, text]);
}

// package.json itself, when the invocation changes it
const pkgNeedsWrite = pkg.version !== version || Number(pkg.build) !== build;

if (checkArg) {
  if (!mismatches.length) {
    console.log(`Version in sync: ${version} (build ${build})`);
    process.exit(0);
  }
  console.error(`Version out of sync — expected ${version} (build ${build}) from package.json:`);
  for (const m of mismatches) {
    console.error(`  ${m.file}: ${m.found === null ? "pattern not found" : `has ${m.found}, want ${m.want}`}`);
  }
  console.error("\nRun `npm run version` to write them.");
  process.exit(1);
}

if (pkgNeedsWrite) {
  pkg.version = version;
  pkg.build = build;
  writeFileSync(at(pkgPath), JSON.stringify(pkg, null, 2) + "\n");
}
for (const [file, text] of writes) writeFileSync(at(file), text);

const touched = [...(pkgNeedsWrite ? [pkgPath] : []), ...writes.map(([f]) => f)];
console.log(
  touched.length
    ? `${version} (build ${build}) → ${touched.join(", ")}`
    : `Already in sync: ${version} (build ${build})`
);
